# Generated by Django 3.2.6 on 2021-09-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Provincializacion', '0003_rename_usuario_usuariotrivia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='texto2',
            field=models.TextField(default=True, verbose_name='Texto de la pregunta numero 2'),
            preserve_default=False,
        ),
    ]
