# Generated by Django 3.2.6 on 2021-09-03 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Provincializacion', '0003_rename_usuario_usuariotrivia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preguntasrespondidas',
            old_name='usuario',
            new_name='triviauser',
        ),
    ]
