# Generated by Django 3.2.6 on 2021-09-02 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Provincializacion', '0004_pregunta_texto2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='texto2',
        ),
    ]
