# Generated by Django 3.2.6 on 2021-09-03 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Provincializacion', '0004_rename_usuario_preguntasrespondidas_triviauser'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='max_puntaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Puntaje Maximo'),
        ),
        migrations.AlterField(
            model_name='elegirrespuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='Provincializacion.pregunta'),
        ),
    ]
