# Generated by Django 3.2.6 on 2021-09-04 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Provincializacion', '0005_remove_pregunta_texto2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preguntasrespondidas',
            old_name='usuario',
            new_name='usuariotrivia',
        ),
    ]
