# Generated by Django 3.2.6 on 2021-09-03 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Provincializacion', '0005_auto_20210903_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='triviauser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='Provincializacion.usuariotrivia'),
        ),
    ]
