# Generated by Django 3.2.6 on 2021-09-04 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Provincializacion', '0008_alter_preguntasrespondidas_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='usuariotrivia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='Provincializacion.usuariotrivia'),
        ),
    ]
