# Generated by Django 3.2.6 on 2021-09-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Provincializacion', '0009_alter_pregunta_max_puntaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='max_puntaje',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=6, verbose_name='Puntaje Maximo'),
        ),
    ]
